import assert from 'node:assert/strict';
import test from 'node:test';
import {
  fitAutoGeneratedNodeDimensions,
  getCenteredAspectCropBox,
} from './generatedImageSizing';

test('calculates a centered crop box for 3:4 portrait framing', () => {
  assert.deepEqual(getCenteredAspectCropBox(900, 1600, '3:4'), {
    x: 0,
    y: 200,
    width: 900,
    height: 1200,
  });
});

test('calculates a centered crop box for 16:9 landscape framing', () => {
  assert.deepEqual(getCenteredAspectCropBox(1600, 1200, '16:9'), {
    x: 0,
    y: 150,
    width: 1600,
    height: 900,
  });
});

test('fits auto-sized generated images without changing their display ratio', () => {
  assert.deepEqual(fitAutoGeneratedNodeDimensions(1536, 1024), {
    width: 520,
    height: 347,
  });
});
