import type { CanvasLayer } from '../types';
import { fitImportedImageDimensions } from './imageImport';

export type SupportedGeneratedAspectRatio = NonNullable<CanvasLayer['aspectRatio']>;
export type FixedGeneratedAspectRatio = Exclude<SupportedGeneratedAspectRatio, 'auto'>;

const TARGET_ASPECT_FACTORS: Record<FixedGeneratedAspectRatio, { w: number; h: number }> = {
  '1:1': { w: 1, h: 1 },
  '3:4': { w: 3, h: 4 },
  '4:3': { w: 4, h: 3 },
  '9:16': { w: 9, h: 16 },
  '16:9': { w: 16, h: 9 },
};

export const FIXED_GENERATION_NODE_DIMS: Record<FixedGeneratedAspectRatio, { w: number; h: number }> = {
  '1:1': { w: 320, h: 320 },
  '3:4': { w: 270, h: 360 },
  '4:3': { w: 360, h: 270 },
  '9:16': { w: 225, h: 400 },
  '16:9': { w: 400, h: 225 },
};

export function isAutoAspectRatio(
  aspectRatio: SupportedGeneratedAspectRatio | undefined,
): aspectRatio is 'auto' {
  return aspectRatio === 'auto';
}

export function getCenteredAspectCropBox(
  sourceWidth: number,
  sourceHeight: number,
  aspectRatio: FixedGeneratedAspectRatio,
): { x: number; y: number; width: number; height: number } {
  const safeSourceWidth = Math.max(1, Math.floor(sourceWidth));
  const safeSourceHeight = Math.max(1, Math.floor(sourceHeight));
  const target = TARGET_ASPECT_FACTORS[aspectRatio];
  const sourceRatio = safeSourceWidth / safeSourceHeight;
  const targetRatio = target.w / target.h;

  let width = safeSourceWidth;
  let height = safeSourceHeight;

  if (Math.abs(sourceRatio - targetRatio) > 0.000001) {
    if (sourceRatio > targetRatio) {
      const candidateWidth = Math.min(
        safeSourceWidth,
        Math.floor((safeSourceHeight * target.w) / target.h),
      );
      width = Math.max(target.w, candidateWidth - (candidateWidth % target.w));
      height = Math.floor((width * target.h) / target.w);
    } else {
      const candidateHeight = Math.min(
        safeSourceHeight,
        Math.floor((safeSourceWidth * target.h) / target.w),
      );
      height = Math.max(target.h, candidateHeight - (candidateHeight % target.h));
      width = Math.floor((height * target.w) / target.h);
    }
  }

  return {
    x: Math.max(0, Math.floor((safeSourceWidth - width) / 2)),
    y: Math.max(0, Math.floor((safeSourceHeight - height) / 2)),
    width,
    height,
  };
}

export function fitAutoGeneratedNodeDimensions(
  sourceWidth: number,
  sourceHeight: number,
): { width: number; height: number } {
  return fitImportedImageDimensions(sourceWidth, sourceHeight);
}
